### ISSUE TITLE
Porque no pones un live preview de la imagen en el README.md

### ISSUE THREAD

**Issue by AlphaTechnolog** [yorkox0/dotfiles#1]
Hola `yorcox0` tu configuracion me parece bastante bonita, ademas de llamativa e intuitiva, pero porque no en ves de poner un link para ver en una pagina el preview de la config, porque no agregas una imagen incrustada de github en markdown en el `README.md`, asi:

```markdown
![prefix](https://i.postimg.cc/KjCnsmGK/2021-10-23-122604-1920x1080-scrot.png)
```

Esto se veria asi:

![prefix](https://i.postimg.cc/KjCnsmGK/2021-10-23-122604-1920x1080-scrot.png)

**Comment by yorkox0** [comment]
Ahora mismo lo pongo!

**Comment by AlphaTechnolog** [comment]
Excelente :)
